#!/bin/bash

# set -e
# set -o pipefail

PROJDIR=$(dirname "$(cd "$(dirname "${0}")"; pwd -P)")

# {{{ Colors
RED='\033[0;31m'
BOLD_RED='\033[1;31m'
GREEN='\033[0;32m'
BOLD_GREEN='\033[1;32m'
YELLOW='\033[0;33m'
BOLD_YELLOW='\033[1;33m'
RESET='\033[0m'
# }}}

# {{{ Help message
function help() {
  cat >&2 << EOF
This script is a driver for "runtime tests".
The "runtime test" is to test gosseract package in specific environments,
such as OS, Go version and Tesseract version.

Options:
  --engine|-e {name}  Specify container engine, either of [docker|podman]. Default: docker.
  --build|-b          Build testable images if provided, otherwise pull images.
  --no-cache|-c       Build testable images without layer cache (only available with -b)
  --push|-p           Push local images to dockerhub (for development purpose).
  --quiet|-q          Don't show verbose logs of setting VMs up.
  --run|-R {case}     Run only cases which have specified pattern in the case names.
  --exclude|-X {case} Run only cases which DON'T have specified pattern in the case names.
  --rm                Remove VMs which are created by this runtime test.
  --list|-l           Just list runtimes
  --help|-h           Show this message ;)

Examples:

  ./test/runtime --build --run CentOS --rm
  ./test/runtime --engine podman --build --run CentOS --rm

EOF
}
# }}}

# {{{ Parse CLI options
function parse_options() {
  ENGINE=docker
  REMOVE=
  BUILD=
  NO_CACHE=
  PUSH=
  QUIET=
  MATCH=
  EXCLUDE=
  LIST=
  while [[ $# -gt 0 ]]; do
  case "${1}" in
      --engine|-e)
      ENGINE="${2}"
      shift && shift
      ;;
      --rm)
      REMOVE=YES
      shift
      ;;
      --build|-b)
      BUILD=YES
      shift
      ;;
      --no-cache|-c)
      NO_CACHE="--no-cache"
      shift
      ;;
      --push|-p)
      PUSH=YES
      shift
      ;;
      --quiet|-q)
      QUIET="--quiet"
      shift
      ;;
      --run|-R)
      MATCH="${2}"
      shift && shift
      ;;
      --exclude|-X)
      EXCLUDE="${2}"
      shift && shift
      ;;
      --list|-l)
      LIST=YES
      shift
      ;;
      --help|-h)
      help && exit 0
      ;;
      *)
      printf "Unkown flag: ${1}\n\n"
      help
      exit 1
      ;;
  esac
  done
}
# }}}

# {{{ Runner function for container runtimes
function test_runtimes() {
  if [ -n "${LIST}" ]; then
    echo "Available runtimes (${ENGINE}):"
    for runtime in `ls ${PROJDIR}/test/runtimes/*.Dockerfile`; do
      testcase=`basename ${runtime} | sed -e s/\.Dockerfile$//`
      echo "  ${testcase}"
    done
    return 0
  fi

  for runtime in `ls ${PROJDIR}/test/runtimes/*.Dockerfile`; do
    testcase=`basename ${runtime} | sed -e s/\.Dockerfile$//`
    if [ -n "${MATCH}" ]; then
      if [[ "${testcase}" != *${MATCH}* ]]; then
        continue
      fi
    fi
    if [ -n "${EXCLUDE}" ]; then
      if [[ "${testcase}" == *${EXCLUDE}* ]]; then
        continue
      fi
    fi
    echo "┌───────────── ${testcase}"
    if [ -n "${BUILD}" ]; then
      echo "│ [${ENGINE}] Building image..."
      ${ENGINE} build . ${NO_CACHE} -f ${runtime} -t gosseract/test:${testcase} ${QUIET} | sed "s/^/│ /"
    else
      echo "│ [${ENGINE}] Pulling image..."
      ${ENGINE} pull gosseract/test:${testcase} ${QUIET} | sed "s/^/│ /"
    fi
    echo "│ [${ENGINE}] Running tests..."
    ${ENGINE} run -i -t -e "TESTCASE=${testcase}" --rm gosseract/test:${testcase} 1>./test/runtimes/TESTRESULT.${testcase}.txt 2>&1
    EXIT_CODE=$?
    cat ./test/runtimes/TESTRESULT.${testcase}.txt | sed "s/^/│ [${testcase}] /"
    if [ ${EXIT_CODE} -gt 0 ]; then
      printf "│ ${BOLD_RED}RUNTIME TEST FAILED! ${testcase}${RESET}\n"
      printf "└───────────── ${testcase} ${BOLD_RED}[NG]${RESET}\n"
      exit ${EXIT_CODE}
    fi
    if [ -n "${PUSH}" ]; then
      echo "│ [${ENGINE}] Pushing the image..."
      ${ENGINE} push gosseract/test:${testcase} | sed "s/^/│ /"
    fi
    if [ -n "${REMOVE}" ]; then
      echo "│ [${ENGINE}] Removing image..."
      ${ENGINE} rmi gosseract/test:${testcase} 1>/dev/null
    fi
    printf "└───────────── ${testcase} ${BOLD_GREEN}[OK]${RESET}\n"
  done
}
# }}}

# {{{ Main procedure
function __main__() {
  parse_options $@
  test_runtimes
}
# }}}

# Entrypoint
__main__ $@
