package gosseract

import (
	"encoding/xml"
)

/**
 * NOTE:
 * 	These structs have been generated by Chidley and
 *  are the a minimum implementation to satisfy test assertions.
 * TODO: Extend structs to cover main usecases.
**/

type AltoPage struct {
	XMLName           xml.Name        `xml:"Page,omitempty" json:"Page,omitempty"`
	AttrHeight        string          `xml:"HEIGHT,attr"  json:",omitempty"`
	AttrID            string          `xml:"ID,attr"  json:",omitempty"`
	AttrPhysicalImgNr string          `xml:"PHYSICAL_IMG_NR,attr"  json:",omitempty"`
	AttrWidth         string          `xml:"WIDTH,attr"  json:",omitempty"`
	AltoPrintSpace    *AltoPrintSpace `xml:"PrintSpace,omitempty" json:"PrintSpace,omitempty"`
}

// AltoPrintSpace has been generated by chidley.
type AltoPrintSpace struct {
	XMLName       xml.Name       `xml:"PrintSpace,omitempty" json:"PrintSpace,omitempty"`
	AttrHeight    string         `xml:"HEIGHT,attr"  json:",omitempty"`
	AttrHpos      string         `xml:"HPOS,attr"  json:",omitempty"`
	AttrVpos      string         `xml:"VPOS,attr"  json:",omitempty"`
	AttrWidth     string         `xml:"WIDTH,attr"  json:",omitempty"`
	AltoTextBlock *AltoTextBlock `xml:"TextBlock,omitempty" json:"TextBlock,omitempty"`
}

// AltoSP has been generated by chidley.
type AltoSP struct {
	XMLName   xml.Name `xml:"SP,omitempty" json:"SP,omitempty"`
	AttrHpos  string   `xml:"HPOS,attr"  json:",omitempty"`
	AttrVpos  string   `xml:"VPOS,attr"  json:",omitempty"`
	AttrWidth string   `xml:"WIDTH,attr"  json:",omitempty"`
}

// AltoString has been generated by chidley.
type AltoString struct {
	XMLName     xml.Name `xml:"String,omitempty" json:"String,omitempty"`
	AttrContent string   `xml:"CONTENT,attr"  json:",omitempty"`
	AttrHeight  string   `xml:"HEIGHT,attr"  json:",omitempty"`
	AttrHpos    string   `xml:"HPOS,attr"  json:",omitempty"`
	AttrID      string   `xml:"ID,attr"  json:",omitempty"`
	AttrVpos    string   `xml:"VPOS,attr"  json:",omitempty"`
	AttrWC      string   `xml:"WC,attr"  json:",omitempty"`
	AttrWidth   string   `xml:"WIDTH,attr"  json:",omitempty"`
}

// AltoTextBlock has been generated by chidley.
type AltoTextBlock struct {
	XMLName      xml.Name        `xml:"TextBlock,omitempty" json:"TextBlock,omitempty"`
	AttrHeight   string          `xml:"HEIGHT,attr"  json:",omitempty"`
	AttrHpos     string          `xml:"HPOS,attr"  json:",omitempty"`
	AttrID       string          `xml:"ID,attr"  json:",omitempty"`
	AttrVpos     string          `xml:"VPOS,attr"  json:",omitempty"`
	AttrWidth    string          `xml:"WIDTH,attr"  json:",omitempty"`
	AltoTextLine []*AltoTextLine `xml:"TextLine,omitempty" json:"TextLine,omitempty"`
}

// AltoTextLine has been generated by chidley.
type AltoTextLine struct {
	XMLName    xml.Name      `xml:"TextLine,omitempty" json:"TextLine,omitempty"`
	AttrHeight string        `xml:"HEIGHT,attr"  json:",omitempty"`
	AttrHpos   string        `xml:"HPOS,attr"  json:",omitempty"`
	AttrID     string        `xml:"ID,attr"  json:",omitempty"`
	AttrVpos   string        `xml:"VPOS,attr"  json:",omitempty"`
	AttrWidth  string        `xml:"WIDTH,attr"  json:",omitempty"`
	AltoSP     []*AltoSP     `xml:"SP,omitempty" json:"SP,omitempty"`
	AltoString []*AltoString `xml:"String,omitempty" json:"String,omitempty"`
}
