name: Vagrant Debug

on:
  workflow_dispatch:
  push:
    branches:
      - 'vagrant/*'

jobs:
  vagrant-test:
    runs-on: macos-10.15
    # runs-on: macos-latest
    # @see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software
    strategy:
      matrix:
        runtime:
          - freebsd
    name: Vagrant ${{ matrix.runtime }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: ${{ matrix.runtime }}
        run: bash ./test/runtime --driver vagrant --build --run ${{ matrix.runtime }}
